[versions]
minecraft = "26.1-snapshot-10"

kotlin = "2.3.10"
coroutines = "1.10.2"

taboolib = "6.2.4"
reflex = "1.2.2"

shadow = "9.3.1"

mixin = "0.8.7"
asm = "9.8"
gson = "2.11.0"
guava = "33.4.0-jre"
jline = "3.30.6"

datafixerupper = "9.0.19"
mojang-logging = "1.6.11"
brigadier = "1.3.10"
log4j = "2.25.2"
netty = "4.2.7.Final"


[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[libraries]
mixin = { module = "org.spongepowered:mixin", version.ref = "mixin" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
jline = { module = "org.jline:jline", version.ref = "jline" }

asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
asm-util = { module = "org.ow2.asm:asm-util", version.ref = "asm" }
asm-commons = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }
asm-tree = { module = "org.ow2.asm:asm-tree", version.ref = "asm" }

reflex = { module = "org.tabooproject.reflex:reflex", version.ref = "reflex" }
reflex-analyser = { module = "org.tabooproject.reflex:analyser", version.ref = "reflex" }

taboolib-common = { module = "io.izzel.taboolib:common", version.ref = "taboolib" }
taboolib-common-platform-api = { module = "io.izzel.taboolib:common-platform-api", version.ref = "taboolib" }
taboolib-common-util = { module = "io.izzel.taboolib:common-util", version.ref = "taboolib" }

mojang-datafixerupper = { module = "com.mojang:datafixerupper", version.ref = "datafixerupper" }
mojang-logging = { module = "com.mojang:logging", version.ref = "mojang-logging" }
mojang-brigadier = { module = "com.mojang:brigadier", version.ref = "brigadier" }

log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }

netty-all = { module = "io.netty:netty-all", version.ref = "netty" }
